IGNORED_NAMED_ENTITY = [
   "AGPL",
   "Cube License",
   "HOLDERS",
   "DATA",
   "THE\n IMPLIED WARRANTIES OF MERCHANTABILITY",
   "HOLDER",
   "http://www.webmproject.org/license/software/",
   "BSD",
   "New License",
   "BSD License",
   "PROVIDED &quot;AS IS&quot",
   "the BSD License",
   "http://www.webmproject.org/license/software/",
   "License-BSD%203--Clause-orange.svg)](https://opensource.org",
   "BSD New",
   "Berkeley Software Distribution",
   "Berkeley Software Distribution License",
   "bsd",
   "The BSD License",
   "Library",
   "THE IMPLIED WARRANTIES OF MERCHANTABILITY",
   "License](https://opensource.org",
   "OSI Certified Open Source Software",
   "POSSIBILITY",
   "Jython 2.0",
   "CONTRIBUTORS BE LIABLE",
   "SOFTWARE",
   "HSQLDB License",
   "THE IMPLIED\n WARRANTIES",
   "BSD Style",
   "EDL",
   "ADMINISTRATION",
   "NO EVENT SHALL Kitware Inc.",
   "LICENSE.txt",
   "base93.c",
   "NO EVENT SHALL BE",
   "Copyright.txt",
   "OSI",
   "License BSD",
   "BSD-3cl](http://directory.fsf.org",
   "BSD-3-Clause",
   "DAMANGE",
   "CAS Java Client",
   "BSD Three Clause License",
   "NewBSD",
   "BSD3 License"
   "BSD3CLAUSE",
   "http://opencv.org/license.html",
   "BSD-Modified"
]